### ISSUE TITLE
icons? ads?

### ISSUE THREAD

**Issue by alexmyczko** [mdoege/AmigaClock#1]
having the clock as an app (macOS or linux) with the original amiga icon?
`pygame.display.set_icon(pygame.image.load('pygame_icon.tiff'))`

to avoid the advertisement when launching from cli:
```
import os
os.environ['PYGAME_HIDE_SUPPORT_PROMPT'] = "hide"
```

i've found the she bang `#!/usr/bin/env python3` to be more portable than just python without 3.

**Comment by mdoege** [comment]
Yes, good ideas, so I've added them. In the original Amiga icon, the clock face is not a circle because of the Amiga's non-square pixels, but I think it still looks okay...
